name: Release ytui-music v2.0.0-beta

on:
  push:
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'LICENSE.txt'
      - 'screenshots/'

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      # - name: Windows build is failing due to mpv.lib not foudn wrror
      #   run: fail now instead later

      - name: Install depencencies
        run: choco install mpv

      - name: Install latest rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Build
        run: |
              cargo build --all --release &&
              for /r %i in (*) do @echo %~ni

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{  github.ref_name }}
          files: target/release/ytui_music-windowns-amd64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
